name: qpod-media-lab

on:
  pull_request:
    paths-ignore:
      - "*.md"

  push:
    branches:
      - master
    paths-ignore:
      - "*.md"

env:
  DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
  DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

jobs:
  qpod_OpenCV:
    name: qpod/opencv
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ./tool.sh
          build_image opencv latest docker_OpenCV/Dockerfile
          push_image

  qpod_OpenFace:
    name: qpod/openface
    needs: qpod_OpenCV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ./tool.sh
          build_image openface latest docker_OpenFace/Dockerfile
          push_image
