name: qpod-media-lab

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "*.md"

  pull_request:
    branches: [ main ]
    paths-ignore:
      - "*.md"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
  DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

jobs:
  qpod_nvidia-docker2:
    name: qpod/nvidia-docker2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: source ./tool.sh && build_image nvidia-docker2 latest		docker_nvidia-docker2/Dockerfile		&& push_image

  qpod_OpenCV:
    name: qpod/opencv
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: source ./tool.sh && build_image opencv latest				docker_OpenCV/Dockerfile				&& push_image


  qpod_PaddleOCR_cuda102:
    name: qpod/paddleocr_cuda102
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: source ./tool.sh && build_image paddleocr-cuda102 latest	docker_PaddleOCR/Dockerfile --build-arg "HF_MODEL_NAME=${HF_MODEL_NAME}"		&& push_image

  qpod_PaddleOCR_cuda116:
    name: qpod/paddleocr_cuda116
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: source ./tool.sh && build_image paddleocr-cuda116 latest	docker_PaddleOCR/Dockerfile --build-arg "HF_MODEL_NAME=${HF_MODEL_NAME}"		&& push_image


  qpod_OpenFace-src:
    name: qpod/openface-src
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: source ./tool.sh && build_image openface-src latest		docker_OpenFace/src.Dockerfile				&& push_image

  qpod_OpenFace:
    name: qpod/openface
    needs: qpod_OpenCV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: source ./tool.sh && build_image openface latest				docker_OpenFace/Dockerfile				&& push_image


  qpod_HuggingFaceModels:
    name: qpod/huggingface-models
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ./tool.sh
          build_image_hf_model() {
            HF_MODEL_NAME=$1; HF_MODEL_TAG=$(echo $1 | sed 's/\//./g');
            echo "Pulling HuggingFace Model: ${HF_MODEL_NAME}..."
            build_image_no_tag huggingface-model ${HF_MODEL_TAG} docker_HuggingFace-models/Dockerfile --build-arg "HF_MODEL_NAME=${HF_MODEL_NAME}" ;
            push_image ;
          }
          export -f build_image_hf_model

          cat docker_HuggingFace-models/list_hf_models.txt | read -r -d '' -a LIST_MODELS_BAK
          LIST_MODELS=("LTP/tiny")
          
          # build_image_hf_model bert-base-cased
          echo ${LIST_MODELS[@]}  | xargs -n 1 -P 10 -I {} bash -c 'build_image_hf_model "$@"' _ {}
